<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net6.0</TargetFrameworks>
    <LangVersion>9.0</LangVersion>
    <PackageId>BakingSheet.Converters.Google</PackageId>
    <Authors>Maxwell Keonwoo Kang</Authors>
    <PackageDescription>BakingSheet importer for Google Sheet</PackageDescription>
    <RepositoryUrl>https://github.com/laicasaane/BakingSheet</RepositoryUrl>
    <CopyOutputSymbolsToPublishDirectory>false</CopyOutputSymbolsToPublishDirectory>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Apis.Drive.v3" Version="1.74.0.4135" />
    <PackageReference Include="Google.Apis.Sheets.v4" Version="1.75.0.4178" />

    <!-- Assemblies already referenced by BakingSheet -->
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.9">
      <IncludeAssets>compile</IncludeAssets>
    </PackageReference>

    <!-- Assemblies already referenced by BakingSheet.Converters.Json -->
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4">
      <IncludeAssets>compile</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BakingSheet\BakingSheet.csproj">
      <Private>False</Private>
    </ProjectReference>
  </ItemGroup>

</Project>
